### ISSUE TITLE
Organisation du dépôt

### ISSUE THREAD

**Issue by Lyokolux** [InfoIsfatesDfhi/cours_prog_proc#1]
On organise ça comment ?
Un dossier `redis` et un `c`

Sinon plus clair avec un dossier `cours` et un autre `exercice`. Les fichiers auront le tag `c` ou `redis` au début du nom selon le sujet ?

Des idées ?

Niveau langues (deusch, english, français), on le fait à l'improvisation ?

**Comment by LucaLeonhardt** [comment]
au pire on fait un vote #demokratie

**Comment by Lyokolux** [comment]
Pour l'organisation, le système de tag sera plus pertinent.

Et pour les langues, c'est open-bar comme chacun le veut.

Voilà c'est finalement réglé.
